export default ()=>[
  {
    path:"technology",
    meta:{
      title:"技术类",
    },
    children:[
      {
        path:"p1",
        meta:{
          title:"技术文章1",
        },
        component:()=>import("./test3.md")
      }
    ],
  },
  {
    path:"p1",
    meta:{
      title:"其他文章之类的",
    },
    component:()=>import("./test2.md")
  }
]